//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chartreuse.Today.ToodleDo.Shared.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ToodleDoResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToodleDoResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chartreuse.Today.ToodleDo.Shared.Resources.ToodleDoResources", typeof(ToodleDoResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string AppBar_Cancel {
            get {
                return ResourceManager.GetString("AppBar_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string AppBar_Save {
            get {
                return ResourceManager.GetString("AppBar_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking credentials....
        /// </summary>
        public static string ToodleDo_CheckingCredentials {
            get {
                return ResourceManager.GetString("ToodleDo_CheckingCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free account at www.toodledo.com.
        /// </summary>
        public static string ToodleDo_Description {
            get {
                return ResourceManager.GetString("ToodleDo_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is empty.
        /// </summary>
        public static string ToodleDo_EmptyPassword {
            get {
                return ResourceManager.GetString("ToodleDo_EmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is empty.
        /// </summary>
        public static string ToodleDo_EmptyUsername {
            get {
                return ResourceManager.GetString("ToodleDo_EmptyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync with ToodleDo.
        /// </summary>
        public static string ToodleDo_Headline {
            get {
                return ResourceManager.GetString("ToodleDo_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials ({0}).
        /// </summary>
        public static string ToodleDo_InvalidCredentialsFormat {
            get {
                return ResourceManager.GetString("ToodleDo_InvalidCredentialsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login in progress....
        /// </summary>
        public static string ToodleDo_LoginInProgress {
            get {
                return ResourceManager.GetString("ToodleDo_LoginInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while obtaining data from server.
        /// </summary>
        public static string ToodleDo_Progress_ErrorWhileGettingData {
            get {
                return ResourceManager.GetString("ToodleDo_Progress_ErrorWhileGettingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login error ({0}).
        /// </summary>
        public static string ToodleDo_Progress_LoginErrorFormat {
            get {
                return ResourceManager.GetString("ToodleDo_Progress_LoginErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization in progress.
        /// </summary>
        public static string ToodleDo_Progress_SyncInProgress {
            get {
                return ResourceManager.GetString("ToodleDo_Progress_SyncInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToodleDo.
        /// </summary>
        public static string ToodleDo_ProviderName {
            get {
                return ResourceManager.GetString("ToodleDo_ProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync error ({0}).
        /// </summary>
        public static string ToodleDo_SyncErrorFormat {
            get {
                return ResourceManager.GetString("ToodleDo_SyncErrorFormat", resourceCulture);
            }
        }
    }
}
