//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chartreuse.Today.Exchange.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExchangeResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExchangeResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chartreuse.Today.Exchange.Resources.ExchangeResources", typeof(ExchangeResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the ActiveSync protocol to sync your tasks.
        /// </summary>
        public static string ActiveSync_Description {
            get {
                return ResourceManager.GetString("ActiveSync_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync with an ActiveSync server.
        /// </summary>
        public static string ActiveSync_Headline {
            get {
                return ResourceManager.GetString("ActiveSync_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActiveSync.
        /// </summary>
        public static string ActiveSync_ProviderName {
            get {
                return ResourceManager.GetString("ActiveSync_ProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-discovery was not found. Try specify the server uri manually..
        /// </summary>
        public static string Exchange_AuthAutoDiscoveryNotFound {
            get {
                return ResourceManager.GetString("Exchange_AuthAutoDiscoveryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials are invalid.
        /// </summary>
        public static string Exchange_AuthInvalidCredential {
            get {
                return ResourceManager.GetString("Exchange_AuthInvalidCredential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credential are valid.
        /// </summary>
        public static string Exchange_AuthOk {
            get {
                return ResourceManager.GetString("Exchange_AuthOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization problem: {0} ({1}).
        /// </summary>
        public static string Exchange_AuthProblemFormat {
            get {
                return ResourceManager.GetString("Exchange_AuthProblemFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server access is forbidden.
        /// </summary>
        public static string Exchange_AuthServerAccessForbiden {
            get {
                return ResourceManager.GetString("Exchange_AuthServerAccessForbiden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server method is not allowed.
        /// </summary>
        public static string Exchange_AuthServerMethodNotAllowed {
            get {
                return ResourceManager.GetString("Exchange_AuthServerMethodNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server uri not found.
        /// </summary>
        public static string Exchange_AuthServerUrlNotFound {
            get {
                return ResourceManager.GetString("Exchange_AuthServerUrlNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trust failure.
        /// </summary>
        public static string Exchange_AuthTrustFailure {
            get {
                return ResourceManager.GetString("Exchange_AuthTrustFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown status.
        /// </summary>
        public static string Exchange_AuthUnkown {
            get {
                return ResourceManager.GetString("Exchange_AuthUnkown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking credentials....
        /// </summary>
        public static string Exchange_CheckingCredentials {
            get {
                return ResourceManager.GetString("Exchange_CheckingCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2007, 2010 or 2013.
        /// </summary>
        public static string Exchange_Description {
            get {
                return ResourceManager.GetString("Exchange_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty email.
        /// </summary>
        public static string Exchange_EmptyEmail {
            get {
                return ResourceManager.GetString("Exchange_EmptyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty password.
        /// </summary>
        public static string Exchange_EmptyPassword {
            get {
                return ResourceManager.GetString("Exchange_EmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty username.
        /// </summary>
        public static string Exchange_EmptyUsername {
            get {
                return ResourceManager.GetString("Exchange_EmptyUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync failed ({0}).
        /// </summary>
        public static string Exchange_ExceptionFormat {
            get {
                return ResourceManager.GetString("Exchange_ExceptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync with Microsoft Exchange.
        /// </summary>
        public static string Exchange_Headline {
            get {
                return ResourceManager.GetString("Exchange_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to login ({0}).
        /// </summary>
        public static string Exchange_InvalidCredentialsFormat {
            get {
                return ResourceManager.GetString("Exchange_InvalidCredentialsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid server Uri.
        /// </summary>
        public static string Exchange_InvalidServerUri {
            get {
                return ResourceManager.GetString("Exchange_InvalidServerUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please remove all existing content from 2Day before trying to configure sync..
        /// </summary>
        public static string Exchange_RemoveExistingContent {
            get {
                return ResourceManager.GetString("Exchange_RemoveExistingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during sync ({0}).
        /// </summary>
        public static string Exchange_SyncErrorFormat {
            get {
                return ResourceManager.GetString("Exchange_SyncErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use &quot;Microsoft Exchange&quot; from the sync settings for Office 365.
        /// </summary>
        public static string ExchangeActiveSync_DomainNotSupported {
            get {
                return ResourceManager.GetString("ExchangeActiveSync_DomainNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either credentials are not valid, or server could not be found.
        /// </summary>
        public static string ExchangeActiveSync_InvalidCredentialsMessage {
            get {
                return ResourceManager.GetString("ExchangeActiveSync_InvalidCredentialsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No task folder found on the server.
        /// </summary>
        public static string ExchangeActiveSync_NoTasksFolder {
            get {
                return ResourceManager.GetString("ExchangeActiveSync_NoTasksFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office 365.
        /// </summary>
        public static string ExchangeOffice365_Description {
            get {
                return ResourceManager.GetString("ExchangeOffice365_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync with Microsoft Office 365.
        /// </summary>
        public static string ExchangeOffice365_Headline {
            get {
                return ResourceManager.GetString("ExchangeOffice365_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office 365.
        /// </summary>
        public static string ExchangeOffice365_SettingsTitle {
            get {
                return ResourceManager.GetString("ExchangeOffice365_SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access your task from the web in outlook.com or from Outlook software.
        /// </summary>
        public static string OutlookActiveSync_Description {
            get {
                return ResourceManager.GetString("OutlookActiveSync_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync with Outlook.com.
        /// </summary>
        public static string OutlookActiveSync_Headline {
            get {
                return ResourceManager.GetString("OutlookActiveSync_Headline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook.com.
        /// </summary>
        public static string OutlookActiveSync_ProviderName {
            get {
                return ResourceManager.GetString("OutlookActiveSync_ProviderName", resourceCulture);
            }
        }
    }
}
