using System;
using Chartreuse.Today.Core.Shared.Tools.Logging;

namespace Chartreuse.Today.Exchange.Ews.Exceptions
{
    /// <summary>
    /// Occurs when the XML generated by a command request is invalid
    /// </summary>
    public class CommandRequestXmlException : Exception
    {
        public CommandRequestXmlException(string message)
            : base(message)
        {
            LogService.Log("CommandRequestXmlException", message);
        }
    }
}