//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chartreuse.Today.Core.Shared.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MarketplaceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MarketplaceResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chartreuse.Today.Core.Shared.Resources.MarketplaceResources", typeof(MarketplaceResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders with icons and colors to organize your tasks.
        /// </summary>
        internal static string Feature1 {
            get {
                return ResourceManager.GetString("Feature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks with priorities, due dates, notes, reminders, recurrences.
        /// </summary>
        internal static string Feature2 {
            get {
                return ResourceManager.GetString("Feature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced customization to better fit your needs.
        /// </summary>
        internal static string Feature3 {
            get {
                return ResourceManager.GetString("Feature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync across all your Windows devices!.
        /// </summary>
        internal static string Feature4 {
            get {
                return ResourceManager.GetString("Feature4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync with Microsoft Exchange, ToodleDo, Microsoft Account or the brand new 2Day Cloud.
        /// </summary>
        internal static string Feature5 {
            get {
                return ResourceManager.GetString("Feature5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTD support (contexts, tags and start dates).
        /// </summary>
        internal static string Feature6 {
            get {
                return ResourceManager.GetString("Feature6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech recognition support.
        /// </summary>
        internal static string Feature7 {
            get {
                return ResourceManager.GetString("Feature7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick-add feature.
        /// </summary>
        internal static string Feature8 {
            get {
                return ResourceManager.GetString("Feature8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The famous Windows Phone to-do list 2Day is now available for your Windows 8 devices!.
        /// </summary>
        internal static string Intro1 {
            get {
                return ResourceManager.GetString("Intro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try 2Day for free for 30 days and you will fall in love with it :-).
        /// </summary>
        internal static string Intro2 {
            get {
                return ResourceManager.GetString("Intro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to todo.
        /// </summary>
        internal static string Keyword1 {
            get {
                return ResourceManager.GetString("Keyword1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to task.
        /// </summary>
        internal static string Keyword2 {
            get {
                return ResourceManager.GetString("Keyword2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gtd.
        /// </summary>
        internal static string Keyword3 {
            get {
                return ResourceManager.GetString("Keyword3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exchange.
        /// </summary>
        internal static string Keyword4 {
            get {
                return ResourceManager.GetString("Keyword4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toodledo.
        /// </summary>
        internal static string Keyword5 {
            get {
                return ResourceManager.GetString("Keyword5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main screen.
        /// </summary>
        internal static string Screen1 {
            get {
                return ResourceManager.GetString("Screen1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync configuration.
        /// </summary>
        internal static string Screen2 {
            get {
                return ResourceManager.GetString("Screen2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag&apos;n&apos;drop support.
        /// </summary>
        internal static string Screen3 {
            get {
                return ResourceManager.GetString("Screen3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick task update.
        /// </summary>
        internal static string Screen4 {
            get {
                return ResourceManager.GetString("Screen4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping configuration.
        /// </summary>
        internal static string Screen5 {
            get {
                return ResourceManager.GetString("Screen5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New task screen.
        /// </summary>
        internal static string Screen6 {
            get {
                return ResourceManager.GetString("Screen6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech recognition.
        /// </summary>
        internal static string Screen7 {
            get {
                return ResourceManager.GetString("Screen7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome screen.
        /// </summary>
        internal static string Screen9 {
            get {
                return ResourceManager.GetString("Screen9", resourceCulture);
            }
        }
    }
}
